#!/bin/zsh

if [ -z $2 ]; then
    printer_name=cosmos_pr1
else
    printer_name=$2
fi

if [ ! -z $1 ] && [ -f $1 ]; then
    name_full=$1
    name_part=`echo $name_full | sed -e "s/^.*\/\([^\/]*\)$/\1/"`
    server=`coins-imac-ssh`
    scp $name_full ${server}:./tmp/$name_part
    ssh $server "env PRINTER=$printer_name LPDEST=$printer_name lpr -o Duplex=DuplexNoTumble ~/tmp/$name_part" | nkf -w
    ssh $server "rm ~/tmp/$name_part" | nkf -w
fi

