#!/bin/zsh

servers=`coins-available | grep "^viola"`
server_num=`echo $servers | wc -l`
random=$RANDOM
selected_server_num=`expr $random % $server_num + 1`
selected_server=`echo $servers | tail -n $selected_server_num | head -n 1`

echo $selected_server
