#!/bin/zsh

# -o landscape : 回転
# -o Duplex=DuplexNoTumble : 両面

LANG=C

usage(){
    echo "Usage: $CMDNAME [-o OPTION] [-p PRINTER] file" 1>&2
    exit 1
}

printer_name=cosmos_pr2
printer_opts=

CMDNAME=`basename $0`

while getopts o:p: OPT
do
    case $OPT in
        "o" ) printer_opts="$printer_opts -o $OPTARG";;
        "p" ) printer_name=$OPTARG;;
          * ) usage;;
    esac
done

shift `expr $OPTIND - 1`

name_full=$1

if [ ! -z $name_full ] && [ -f $name_full ]; then
    name_part=`echo $name_full | sed -e "s/^.*\/\([^\/]*\)$/\1/"`
    server=`coins-imac`
    ssh -S ~/.ssh/master-$$ $server -M -f -N 2>/dev/null 1>&2
    scp -o ControlPath=~/.ssh/master-$$ $name_full ${server}:./tmp/$name_part
    ssh -S ~/.ssh/master-$$ $server \
        "env PRINTER=$printer_name LPDEST=$printer_name \
        lpr $printer_opts ~/tmp/$name_part"
    ssh -S ~/.ssh/master-$$ $server "rm ~/tmp/$name_part"
    ssh -S ~/.ssh/master-$$ $server -O exit 1>/dev/null 2>/dev/null
else
    usage
fi
